# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0e8017b495afab7f02fb189be8f4f25dc04292f1da2a4822257a6955d39f570d2e285f188f42884e4424f5e5c1ce92cbebd1869ff983203f727ce2ae5a06342

test:
  secret_key_base: 988896526301d6ff45296d8a0c8098b4a679a97789fb2911bc326dfc90b81c4bdbc891d8ae6da5a01b7f671291b07022b8f21077b256fc1a5db2ad0de74746aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
